In [1]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt

from catboost import Pool, CatBoostClassifier, CatBoostRegressor, CatBoostRanker
from sklearn.metrics import roc_auc_score
from sklearn.metrics import average_precision_score, precision_recall_curve, auc

In [2]:
data_path = '/media/dm/1TB/Data Fusion Contest 2026/task1/'

customer_id – id клиента банка
event_id — id операции
event_dttm – дата/время операции
event_type_nm – тип операции
event_desc – закодировнное описание операции
channel_indicator_type – канал совершения операции
channel_indicator_subtype – подтип канала совершения операции
operaton_amt — сумма операции в рублях
currency_iso_cd – валюта операции
mcc_code – группа MCC merchant_category_code
pos_cd – закодированное значение point of sale condition code
accept_language – язык заголовка http запроса
browser_language – язык браузера
timezone — часовой пояс
session_id – идентификатор сессии
operating_system_type – закодированное значение операционной системы
battery – заряд устройства
device_system_version – версия операционной системы
screen_size – разрешение экрана
developer_tools — настройки разработчика (флаг на устройстве)
phone_voip_call_state – флаг события VoIP-звонка во время проведения операции
web_rdp_connection – флаг наличия удаленного управления над устройством
compromised – наличие Root-доступа на устройстве

In [3]:
%%time
#экономия ОЗУ
train = pl.concat([
        pl.scan_parquet(data_path+'pretrain_part_*.parquet'
                          ).with_columns(pl.lit(True).alias("pretrain"),
                                         pl.col("session_id").cast(pl.Int64)
                                        ),
        pl.scan_parquet(data_path+'train_part_*.parquet'
                          ).with_columns(pl.lit(False).alias("pretrain")),
                   ]
                          ).with_columns(pl.col('event_dttm').str.to_datetime(),
                                         
                                         pl.col("event_type_nm").cast(pl.Int8),
                                         pl.col("event_desc").cast(pl.UInt8),
                                         pl.col("channel_indicator_type").cast(pl.Int8),
                                         pl.col("channel_indicator_sub_type").cast(pl.Int8),
                                         pl.col("currency_iso_cd").cast(pl.Int8),
                                         #pl.col("operaton_amt").log1p().cast(pl.Float32),
                                         pl.col("mcc_code").cast(pl.Int8),
                                         pl.col("pos_cd").cast(pl.Int8),
                                         pl.col("timezone").cast(pl.UInt16),
                                         pl.col("operating_system_type").cast(pl.Int8),
                                         pl.col("developer_tools").cast(pl.Int8),
                                         pl.col("phone_voip_call_state").cast(pl.Int8),
                                         pl.col("web_rdp_connection").cast(pl.Int8),
                                         pl.col("compromised").cast(pl.Int8),
                                         #pl.col("device_system_version").cast(pl.Int8),
                                         pl.col("device_system_version").is_null(),
                                         #pl.col("battery").fill_null("-99%").str.replace("not available","-90%"
                                         #                ).str.split("%").list.first().str.replace_all(":","").cast(pl.Float32).fill_nan(105).round().cast(pl.Int8),
                                         pl.col("battery").is_null(),
                                         pl.col("browser_language").is_null(),
                                         pl.col("screen_size").str.replace_all(" ","").str.split("x"),
                          ).with_columns(
                                         pl.col("screen_size").list.first().cast(pl.Float32).alias("screen_w"),
                                         pl.col("screen_size").list.last().cast(pl.Float32).alias("screen_h"),
                          ).with_columns( (pl.col('screen_w')/pl.col('screen_h')*40).round().cast(pl.UInt8).alias("screen_"),
                                        ).drop("screen_size","accept_language"
                          ).sort("customer_id","event_dttm"
               ).fill_null(-1
               ).fill_null("null"
                                ).collect()
train

CPU times: user 2min 57s, sys: 50.5 s, total: 3min 47s
Wall time: 1min 31s

shape: (176_617_797, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ customer_i ┆ event_id   ┆ event_dttm ┆ event_type ┆ … ┆ pretrain ┆ screen_w ┆ screen_h ┆ screen_ │
│ d          ┆ ---        ┆ ---        ┆ _nm        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ ---        ┆ i64        ┆ datetime[μ ┆ ---        ┆   ┆ bool     ┆ f32      ┆ f32      ┆ i16     │
│ i64        ┆            ┆ s]         ┆ i8         ┆   ┆          ┆          ┆          ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ 1231231231 ┆ 1232519722 ┆ 2023-10-01 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 61925      ┆ 09:16:41   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1251932981 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 64858      ┆ 11:13:48   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1248239322 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 44729      ┆ 11:40:35   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1244545633 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 99321      ┆ 16:37:32   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1264903778 ┆ 2023-10-02 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 86229      ┆ 19:28:25   ┆            ┆   ┆          ┆          ┆          ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ 1242655844 ┆ 1254166374 ┆ 2025-05-24 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 35562      ┆ 06:48:12   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1238274984 ┆ 2025-05-24 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 03451      ┆ 06:50:19   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1253307400 ┆ 2025-05-24 ┆ 14         ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 18955      ┆ 06:50:41   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1246693116 ┆ 2025-05-31 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 07029      ┆ 10:49:16   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1240937867 ┆ 2025-05-31 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 50346      ┆ 10:52:01   ┆            ┆   ┆          ┆          ┆          ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴─────────┘

In [6]:
cols = [
#"event_dttm",
"event_type_nm",
"event_desc",
"channel_indicator_type",
"channel_indicator_sub_type",
"operaton_amt",
"currency_iso_cd",
"mcc_code",
"pos_cd",
#"accept_language",
"browser_language",
"timezone",
"session_id",
"operating_system_type",
"battery",
"device_system_version",
#"screen_size",
"developer_tools",
"phone_voip_call_state",
"web_rdp_connection",
"compromised"
]

In [4]:
%%time
#Генерация свойств по предистории 
train0 = train.with_columns(
                   (pl.col("event_dttm")-pl.col("event_dttm").shift(1).over("customer_id")).dt.total_seconds().alias("pause_cus"),
                   (pl.col("event_dttm")-pl.col("event_dttm").shift(1).over("session_id")).dt.total_seconds().alias("pause_ses"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id").alias("operaton_amt_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","mcc_code").alias("operaton_amt_mcc_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","channel_indicator_type").alias("operaton_amt_type_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","event_desc").alias("operaton_amt_desc_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","channel_indicator_sub_type").alias("operaton_amt_sub_max_prev"),
                   pl.lit(1).alias("one") 
                  )

for col in cols:
    print(col, end=" ")
    train0 = train0.with_columns(
                                 (pl.col(col) == pl.col(col).shift(1).over("customer_id")).alias(f"{col}_prev"),
                                 pl.col("one").rolling_sum(window_size=9999999,min_samples=1).log1p().cast(pl.Float32).over("customer_id",col).alias(f"{col}_log_count"),
                                )
train0 = train0.with_columns(pl.col("one").rolling_sum(window_size=9999999,min_samples=0
                                                      ).cast(pl.UInt16).over("customer_id","session_id").alias(f"{col}_ses_count"),
                            )
train0

event_type_nm event_desc channel_indicator_type channel_indicator_sub_type operaton_amt currency_iso_cd mcc_code pos_cd browser_language timezone session_id operating_system_type battery device_system_version developer_tools phone_voip_call_state web_rdp_connection compromised CPU times: user 17min 53s, sys: 56.5 s, total: 18min 49s
Wall time: 5min 59s

shape: (176_617_797, 70)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ event_id  ┆ event_dtt ┆ event_typ ┆ … ┆ web_rdp_c ┆ compromis ┆ compromis ┆ compromi │
│ id        ┆ ---       ┆ m         ┆ e_nm      ┆   ┆ onnection ┆ ed_prev   ┆ ed_log_co ┆ sed_ses_ │
│ ---       ┆ i64       ┆ ---       ┆ ---       ┆   ┆ _log_coun ┆ ---       ┆ unt       ┆ count    │
│ i64       ┆           ┆ datetime[ ┆ i8        ┆   ┆ t         ┆ bool      ┆ ---       ┆ ---      │
│           ┆           ┆ μs]       ┆           ┆   ┆ ---       ┆           ┆ f32       ┆ u16      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 123123123 ┆ 123251972 ┆ 2023-10-0 ┆ 7         ┆ … ┆ 0.693147  ┆ null      ┆ 0.693147  ┆ 1        │
│ 123129    ┆ 261925    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 09:16:41  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 125193298 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.098612  ┆ true      ┆ 1.098612  ┆ 2        │
│ 123129    ┆ 164858    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 11:13:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 124823932 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.386294  ┆ true      ┆ 1.386294  ┆ 3        │
│ 123129    ┆ 244729    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 11:40:35  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 124454563 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.609438  ┆ true      ┆ 1.609438  ┆ 4        │
│ 123129    ┆ 399321    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 16:37:32  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 126490377 ┆ 2023-10-0 ┆ 7         ┆ … ┆ 1.791759  ┆ true      ┆ 1.791759  ┆ 5        │
│ 123129    ┆ 886229    ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 19:28:25  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 124265584 ┆ 125416637 ┆ 2025-05-2 ┆ 7         ┆ … ┆ 6.688354  ┆ true      ┆ 5.384495  ┆ 1        │
│ 425461    ┆ 435562    ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 06:48:12  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 123827498 ┆ 2025-05-2 ┆ 7         ┆ … ┆ 6.689599  ┆ true      ┆ 5.389072  ┆ 1        │
│ 425461    ┆ 403451    ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 06:50:19  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 125330740 ┆ 2025-05-2 ┆ 14        ┆ … ┆ 6.690842  ┆ true      ┆ 5.393628  ┆ 2        │
│ 425461    ┆ 018955    ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 06:50:41  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 124669311 ┆ 2025-05-3 ┆ 7         ┆ … ┆ 6.692084  ┆ true      ┆ 5.398163  ┆ 1        │
│ 425461    ┆ 607029    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:49:16  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 124093786 ┆ 2025-05-3 ┆ 7         ┆ … ┆ 6.693324  ┆ true      ┆ 5.402678  ┆ 1        │
│ 425461    ┆ 750346    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:52:01  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
train0.write_parquet("train0.pq")
train0.shape

(176617797, 70)

In [6]:
#train0 = pl.read_parquet("train0.pq")
#train0.shape

In [7]:
%%time
#наклейка меток
labels = pl.scan_parquet(data_path+'train_labels.parquet'
                        ).with_columns(pl.col('target').cast(pl.Boolean),
                        ).collect(
         ).join(train0.filter(~pl.col("pretrain")
                             ).drop("pretrain","customer_id"),
                on=[#"customer_id",
                    "event_id"],
                how="right"
        ).with_columns( pl.col("target").is_not_null().alias("label")
               ).fill_null(False
)
labels
#shape: (87_514, 3)
#shape: (85_677_840, 49)

CPU times: user 14.9 s, sys: 15.4 s, total: 30.2 s
Wall time: 5.35 s

shape: (85_677_840, 71)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────┐
│ customer_i ┆ target ┆ event_id   ┆ event_dttm ┆ … ┆ compromise ┆ compromise ┆ compromise ┆ label │
│ d          ┆ ---    ┆ ---        ┆ ---        ┆   ┆ d_prev     ┆ d_log_coun ┆ d_ses_coun ┆ ---   │
│ ---        ┆ bool   ┆ i64        ┆ datetime[μ ┆   ┆ ---        ┆ t          ┆ t          ┆ bool  │
│ i64        ┆        ┆            ┆ s]         ┆   ┆ bool       ┆ ---        ┆ ---        ┆       │
│            ┆        ┆            ┆            ┆   ┆            ┆ f32        ┆ u16        ┆       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════╡
│ null       ┆ false  ┆ 1239993003 ┆ 2024-10-01 ┆ … ┆ true       ┆ 7.323831   ┆ 1515       ┆ false │
│            ┆        ┆ 82879      ┆ 05:29:14   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1245318757 ┆ 2024-10-01 ┆ … ┆ true       ┆ 7.32449    ┆ 1516       ┆ false │
│            ┆        ┆ 13936      ┆ 10:17:22   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1233292855 ┆ 2024-10-01 ┆ … ┆ true       ┆ 7.325149   ┆ 1517       ┆ false │
│            ┆        ┆ 80171      ┆ 10:20:03   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1243343054 ┆ 2024-10-02 ┆ … ┆ true       ┆ 7.325808   ┆ 1518       ┆ false │
│            ┆        ┆ 30665      ┆ 07:48:09   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1262155011 ┆ 2024-10-02 ┆ … ┆ true       ┆ 7.326466   ┆ 1519       ┆ false │
│            ┆        ┆ 46513      ┆ 11:20:40   ┆   ┆            ┆            ┆            ┆       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …     │
│ null       ┆ false  ┆ 1254166374 ┆ 2025-05-24 ┆ … ┆ true       ┆ 5.384495   ┆ 1          ┆ false │
│            ┆        ┆ 35562      ┆ 06:48:12   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1238274984 ┆ 2025-05-24 ┆ … ┆ true       ┆ 5.389072   ┆ 1          ┆ false │
│            ┆        ┆ 03451      ┆ 06:50:19   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1253307400 ┆ 2025-05-24 ┆ … ┆ true       ┆ 5.393628   ┆ 2          ┆ false │
│            ┆        ┆ 18955      ┆ 06:50:41   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1246693116 ┆ 2025-05-31 ┆ … ┆ true       ┆ 5.398163   ┆ 1          ┆ false │
│            ┆        ┆ 07029      ┆ 10:49:16   ┆   ┆            ┆            ┆            ┆       │
│ null       ┆ false  ┆ 1240937867 ┆ 2025-05-31 ┆ … ┆ true       ┆ 5.402678   ┆ 1          ┆ false │
│            ┆        ┆ 50346      ┆ 10:52:01   ┆   ┆            ┆            ┆            ┆       │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────┘

In [8]:
cat_feature_names = []

In [9]:
%%time
limit=round( labels.shape[0]*0.6 )

###если тренировать только на меченом
#train_pool = Pool(data = labels[:limit].filter(pl.col("label")).drop(#"weight", 
###если тренировать на всем трейне
train_pool = Pool(data = labels[:limit].drop(#"weight", #если тренировать на всем трейне
                                             "customer_id","target","event_id","event_dttm","session_id","label"
                                      ).to_pandas(), 
###если тренировать только на меченом
#                      label = labels[:limit].filter(pl.col("label")).select("target"
###если тренировать на всем трейне
                      label = labels[:limit].select("target"
                                           ).to_pandas(), 
                      cat_features = cat_feature_names
                     )

###оценивать только на меченом
valid_pool = Pool(data = labels[limit:].filter(pl.col("label")
                                      ).drop(#"weight",
                                             "customer_id","target","event_id","event_dttm","session_id","label"
                                      ).to_pandas(), 
                      label = labels[limit:].filter(pl.col("label")
                                      ).select("target"
                                      ).to_pandas(), 
                      cat_features = cat_feature_names
                     )
valid_pool

CPU times: user 8.91 s, sys: 30.9 s, total: 39.8 s
Wall time: 6.48 s

In [10]:
model = CatBoostClassifier(
                            depth=7,
                           loss_function = 'Logloss',
                           #loss_function = 'Focal:focal_alpha=0.5;focal_gamma=0.1',
                           custom_metric=["Accuracy",'Logloss',"Precision","Recall",
                                          "F1","AUC","PRAUC"],
    
                           eval_metric="PRAUC",
                           #eval_metric=MyMetric(),
                           random_seed = 1234,
    
                           task_type="GPU",
                           verbose = 100)

In [11]:
%%time

model.fit(train_pool,
              plot=True,
              eval_set=valid_pool,
              early_stopping_rounds=200,
              verbose = 1000
             )
model.save_model(f"model00.cbm")
print(model.get_feature_importance(prettified=True))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.02832

Default metric period is 5 because AUC, PRAUC is/are not implemented for GPU
Metric PRAUC is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time
Metric PRAUC is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0

0:	learn: 0.0055365	test: 0.5984335	best: 0.5984335 (0)	total: 2.31s	remaining: 38m 28s

Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0

Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0
Number of the positive class predictions is 0. Setting Precision metric value to the default 0

999:	learn: 0.0279821	test: 0.7368839	best: 0.7368839 (999)	total: 27m 27s	remaining: 0us
bestTest = 0.7368838602
bestIteration = 999
                    Feature Id  Importances
0                 operaton_amt    11.854271
1             pos_cd_log_count     7.729910
2                    pause_cus     6.761138
3                     mcc_code     5.992036
4                   event_desc     5.756007
..                         ...          ...
60     web_rdp_connection_prev     0.035497
61               timezone_prev     0.024503
62       browser_language_prev     0.022477
63  device_system_version_prev     0.016751
64                         one     0.000000

[65 rows x 2 columns]
CPU times: user 30min 42s, sys: 5min 17s, total: 36min
Wall time: 27min 39s

In [12]:
model.get_feature_importance(prettified=True).head(60)

                              Feature Id  Importances
0                           operaton_amt    11.854271
1                       pos_cd_log_count     7.729910
2                              pause_cus     6.761138
3                               mcc_code     5.992036
4                             event_desc     5.756007
5                   event_desc_log_count     5.281206
6                              pause_ses     4.929393
7                     mcc_code_log_count     4.222202
8             operaton_amt_desc_max_prev     4.163511
9                          event_type_nm     2.721051
10                 operaton_amt_max_prev     2.708267
11             operaton_amt_mcc_max_prev     2.659049
12                    timezone_log_count     2.377250
13            operaton_amt_type_max_prev     2.332373
14                         mcc_code_prev     2.079132
15                                pos_cd     1.834448
16            channel_indicator_sub_type     1.686310
17               event_type_nm_log_count     1.633029
18      channel_indicator_type_log_count     1.625552
19                 operating_system_type     1.408051
20                 compromised_log_count     1.311089
21                channel_indicator_type     1.306406
22  channel_indicator_sub_type_log_count     1.267881
23                 compromised_ses_count     1.126041
24             operaton_amt_sub_max_prev     1.077509
25                    event_type_nm_prev     1.071043
26                              screen_h     0.985831
27                  session_id_log_count     0.963719
28             developer_tools_log_count     0.942355
29       device_system_version_log_count     0.856773
30                       event_desc_prev     0.837572
31                 phone_voip_call_state     0.683245
32                              timezone     0.640122
33             currency_iso_cd_log_count     0.625716
34                           pos_cd_prev     0.621701
35       operating_system_type_log_count     0.568848
36                      browser_language     0.530543
37       phone_voip_call_state_log_count     0.513753
38                               battery     0.446937
39          web_rdp_connection_log_count     0.369704
40            browser_language_log_count     0.332981
41                  currency_iso_cd_prev     0.325082
42                               screen_     0.308994
43                 device_system_version     0.255690
44                    web_rdp_connection     0.242780
45                              screen_w     0.227538
46                operaton_amt_log_count     0.217993
47                       currency_iso_cd     0.182326
48       channel_indicator_sub_type_prev     0.182148
49                     operaton_amt_prev     0.167435
50                     battery_log_count     0.161697
51                       developer_tools     0.141883
52                      compromised_prev     0.128283
53                  developer_tools_prev     0.115157
54                       session_id_prev     0.092034
55            phone_voip_call_state_prev     0.083697
56           channel_indicator_type_prev     0.078140
57                           compromised     0.064893
58                          battery_prev     0.048354
59            operating_system_type_prev     0.042694

In [13]:
average_precision_score(labels[limit:].filter(pl.col("label")
                                      ).select("target"
                                      ).to_pandas(),
                        model.predict_proba(valid_pool)[:,1]
                       )

0.7369119110755996

In [14]:
precisions, recalls, _ = precision_recall_curve(labels[limit:].filter(pl.col("label")
                                      ).select("target"
                                      ).to_pandas(),
                        model.predict_proba(valid_pool)[:,0])
auc(recalls, precisions)

0.4738131745665183

In [3]:
%%time
test = pl.concat([
        pl.scan_parquet(data_path+'pretrain_part_*.parquet'
                          ).with_columns(pl.lit(True).alias("pretrain"),
                                         pl.col("session_id").cast(pl.Int64)
                                        ),
        pl.scan_parquet(data_path+'train_part_*.parquet'
                          ).with_columns(pl.lit(True).alias("pretrain")),    
    
        pl.scan_parquet(data_path+'pretest.parquet'
                          ).with_columns(pl.lit(True).alias("pretrain"),
                                         pl.col("session_id").cast(pl.Int64)
                                        ),
        pl.scan_parquet(data_path+'test.parquet'
                          ).with_columns(pl.lit(False).alias("pretrain")),
                   ]
                          ).with_columns(pl.col('event_dttm').str.to_datetime(),
                                         
                                         pl.col("event_type_nm").cast(pl.Int8),
                                         pl.col("event_desc").cast(pl.UInt8),
                                         pl.col("channel_indicator_type").cast(pl.Int8),
                                         pl.col("channel_indicator_sub_type").cast(pl.Int8),
                                         pl.col("currency_iso_cd").cast(pl.Int8),
                                         #pl.col("operaton_amt").log1p().cast(pl.Float32),
                                         pl.col("mcc_code").cast(pl.Int8),
                                         pl.col("pos_cd").cast(pl.Int8),
                                         pl.col("timezone").cast(pl.UInt16),
                                         pl.col("operating_system_type").cast(pl.Int8),
                                         pl.col("developer_tools").cast(pl.Int8),
                                         pl.col("phone_voip_call_state").cast(pl.Int8),
                                         pl.col("web_rdp_connection").cast(pl.Int8),
                                         pl.col("compromised").cast(pl.Int8),
                                         pl.col("battery").is_null(),
                                         pl.col("device_system_version").is_null(),
                                         pl.col("browser_language").is_null(),
                                         pl.col("screen_size").str.replace_all(" ","").str.split("x"),
                          ).with_columns(
                                         pl.col("screen_size").list.first().cast(pl.Float32).alias("screen_w"),
                                         pl.col("screen_size").list.last().cast(pl.Float32).alias("screen_h"),
                          ).with_columns( (pl.col('screen_w')/pl.col('screen_h')*40).round().cast(pl.Int16).alias("screen_"),
                                        ).drop("screen_size","accept_language"
                        ).sort("customer_id","event_id"
               ).fill_null(-1
               ).fill_null("null"
                                ).collect()
test
#shape: (14_835_758, 24)
#shape: (191_453_555, 24)

CPU times: user 3min 21s, sys: 52.7 s, total: 4min 13s
Wall time: 1min 50s

shape: (191_453_555, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ customer_i ┆ event_id   ┆ event_dttm ┆ event_type ┆ … ┆ pretrain ┆ screen_w ┆ screen_h ┆ screen_ │
│ d          ┆ ---        ┆ ---        ┆ _nm        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ ---        ┆ i64        ┆ datetime[μ ┆ ---        ┆   ┆ bool     ┆ f32      ┆ f32      ┆ i16     │
│ i64        ┆            ┆ s]         ┆ i8         ┆   ┆          ┆          ┆          ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ 1231231231 ┆ 1231231235 ┆ 2024-01-03 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 84584      ┆ 12:37:20   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1231231251 ┆ 2025-01-30 ┆ 7          ┆ … ┆ true     ┆ 1080.0   ┆ 2180.0   ┆ 20      │
│ 23129      ┆ 28477      ┆ 14:25:45   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1231231268 ┆ 2024-10-20 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 51900      ┆ 16:28:40   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1231231274 ┆ 2025-06-26 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 56830      ┆ 05:46:09   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1231317136 ┆ 2024-10-14 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 80603      ┆ 16:51:11   ┆            ┆   ┆          ┆          ┆          ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ 1242655844 ┆ 1265419181 ┆ 2024-05-29 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 25461      ┆ 74987      ┆ 07:43:38   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1265419182 ┆ 2024-02-23 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 25461      ┆ 61472      ┆ 16:12:17   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1265419184 ┆ 2024-06-29 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 25461      ┆ 79371      ┆ 19:17:13   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1265419186 ┆ 2024-01-12 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 25461      ┆ 63129      ┆ 05:27:12   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1265505094 ┆ 2025-04-09 ┆ 7          ┆ … ┆ true     ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 96907      ┆ 12:48:42   ┆            ┆   ┆          ┆          ┆          ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴─────────┘

In [4]:
%%time
#удаление дублей по event_id
test = test.with_columns( (pl.col("event_id")==pl.col("event_id").shift(1)).alias("double")
                 ).filter(pl.col("double")==False
                         ).drop("double"
                               ).sort("customer_id","event_dttm"
                                     )
test
#shape: (191_310_789, 24)

CPU times: user 1min 17s, sys: 8.52 s, total: 1min 26s
Wall time: 17.3 s

shape: (191_310_789, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ customer_i ┆ event_id   ┆ event_dttm ┆ event_type ┆ … ┆ pretrain ┆ screen_w ┆ screen_h ┆ screen_ │
│ d          ┆ ---        ┆ ---        ┆ _nm        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ ---        ┆ i64        ┆ datetime[μ ┆ ---        ┆   ┆ bool     ┆ f32      ┆ f32      ┆ i16     │
│ i64        ┆            ┆ s]         ┆ i8         ┆   ┆          ┆          ┆          ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ 1231231231 ┆ 1232519722 ┆ 2023-10-01 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 61925      ┆ 09:16:41   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1251932981 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 64858      ┆ 11:13:48   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1248239322 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 44729      ┆ 11:40:35   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1244545633 ┆ 2023-10-01 ┆ 14         ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 99321      ┆ 16:37:32   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1231231231 ┆ 1264903778 ┆ 2023-10-02 ┆ 7          ┆ … ┆ true     ┆ -1.0     ┆ -1.0     ┆ -1      │
│ 23129      ┆ 86229      ┆ 19:28:25   ┆            ┆   ┆          ┆          ┆          ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ 1242655844 ┆ 1259320359 ┆ 2025-06-23 ┆ 7          ┆ … ┆ true     ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 70896      ┆ 04:43:35   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1262670423 ┆ 2025-06-26 ┆ 7          ┆ … ┆ true     ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 26129      ┆ 05:15:27   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1238704511 ┆ 2025-06-26 ┆ 7          ┆ … ┆ true     ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 72166      ┆ 05:16:37   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1251932998 ┆ 2025-06-28 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 28684      ┆ 02:47:37   ┆            ┆   ┆          ┆          ┆          ┆         │
│ 1242655844 ┆ 1256571563 ┆ 2025-06-28 ┆ 7          ┆ … ┆ false    ┆ 1080.0   ┆ 2168.0   ┆ 20      │
│ 25461      ┆ 03168      ┆ 02:48:31   ┆            ┆   ┆          ┆          ┆          ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴─────────┘

In [7]:
%%time
test0 = test.with_columns(
                   (pl.col("event_dttm")-pl.col("event_dttm").shift(1).over("customer_id")).dt.total_seconds().alias("pause_cus"),
                   (pl.col("event_dttm")-pl.col("event_dttm").shift(1).over("session_id")).dt.total_seconds().alias("pause_ses"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id").alias("operaton_amt_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","mcc_code").alias("operaton_amt_mcc_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","channel_indicator_type").alias("operaton_amt_type_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","event_desc").alias("operaton_amt_desc_max_prev"),
                   pl.col("operaton_amt").rolling_max(window_size=9999999,min_samples=1).over("customer_id","channel_indicator_sub_type").alias("operaton_amt_sub_max_prev"),
                   pl.lit(1).alias("one") 
                  )
for col in cols:
    print(col, end=" ")
    test0 = test0.with_columns(
                                 (pl.col(col) == pl.col(col).shift(1).over("customer_id")).alias(f"{col}_prev"),
                                 pl.col("one").rolling_sum(window_size=9999999,min_samples=1).log1p().cast(pl.Float32).over("customer_id",col).alias(f"{col}_log_count"),
                                )
test0 = test0.with_columns(pl.col("one").rolling_sum(window_size=9999999,min_samples=0
                                                      ).cast(pl.UInt16).over("customer_id","session_id").alias(f"{col}_ses_count"),
                            )
test0

event_type_nm event_desc channel_indicator_type channel_indicator_sub_type operaton_amt currency_iso_cd mcc_code pos_cd browser_language timezone session_id operating_system_type battery device_system_version developer_tools phone_voip_call_state web_rdp_connection compromised CPU times: user 19min 34s, sys: 1min 11s, total: 20min 45s
Wall time: 6min 40s

shape: (191_310_789, 70)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ event_id  ┆ event_dtt ┆ event_typ ┆ … ┆ web_rdp_c ┆ compromis ┆ compromis ┆ compromi │
│ id        ┆ ---       ┆ m         ┆ e_nm      ┆   ┆ onnection ┆ ed_prev   ┆ ed_log_co ┆ sed_ses_ │
│ ---       ┆ i64       ┆ ---       ┆ ---       ┆   ┆ _log_coun ┆ ---       ┆ unt       ┆ count    │
│ i64       ┆           ┆ datetime[ ┆ i8        ┆   ┆ t         ┆ bool      ┆ ---       ┆ ---      │
│           ┆           ┆ μs]       ┆           ┆   ┆ ---       ┆           ┆ f32       ┆ u16      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 123123123 ┆ 123251972 ┆ 2023-10-0 ┆ 7         ┆ … ┆ 0.693147  ┆ null      ┆ 0.693147  ┆ 1        │
│ 123129    ┆ 261925    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 09:16:41  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 125193298 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.098612  ┆ true      ┆ 1.098612  ┆ 2        │
│ 123129    ┆ 164858    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 11:13:48  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 124823932 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.386294  ┆ true      ┆ 1.386294  ┆ 3        │
│ 123129    ┆ 244729    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 11:40:35  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 124454563 ┆ 2023-10-0 ┆ 14        ┆ … ┆ 1.609438  ┆ true      ┆ 1.609438  ┆ 4        │
│ 123129    ┆ 399321    ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 16:37:32  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123123123 ┆ 126490377 ┆ 2023-10-0 ┆ 7         ┆ … ┆ 1.791759  ┆ true      ┆ 1.791759  ┆ 5        │
│ 123129    ┆ 886229    ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 19:28:25  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 124265584 ┆ 125932035 ┆ 2025-06-2 ┆ 7         ┆ … ┆ 6.700731  ┆ true      ┆ 5.429346  ┆ 1        │
│ 425461    ┆ 970896    ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 04:43:35  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 126267042 ┆ 2025-06-2 ┆ 7         ┆ … ┆ 6.701961  ┆ true      ┆ 5.433722  ┆ 1        │
│ 425461    ┆ 326129    ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 05:15:27  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 123870451 ┆ 2025-06-2 ┆ 7         ┆ … ┆ 6.703188  ┆ true      ┆ 5.438079  ┆ 1        │
│ 425461    ┆ 172166    ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 05:16:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 125193299 ┆ 2025-06-2 ┆ 7         ┆ … ┆ 6.704414  ┆ true      ┆ 5.442418  ┆ 1        │
│ 425461    ┆ 828684    ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 02:47:37  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124265584 ┆ 125657156 ┆ 2025-06-2 ┆ 7         ┆ … ┆ 6.705639  ┆ true      ┆ 5.446737  ┆ 1        │
│ 425461    ┆ 303168    ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 02:48:31  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
%%time
submit = pl.read_csv(data_path+'sample_submit.csv')
submit
#shape: (633_683, 2)

CPU times: user 193 ms, sys: 29.7 ms, total: 223 ms
Wall time: 436 ms

shape: (633_683, 2)
┌─────────────────┬───────────┐
│ event_id        ┆ predict   │
│ ---             ┆ ---       │
│ i64             ┆ f64       │
╞═════════════════╪═══════════╡
│ 125854726334416 ┆ -0.984226 │
│ 125949211749418 ┆ -1.14122  │
│ 124437385134670 ┆ -0.869487 │
│ 124394437682654 ┆ -0.869487 │
│ 123973531121838 ┆ -1.039899 │
│ …               ┆ …         │
│ 125304968700392 ┆ -1.196618 │
│ 123930579661188 ┆ -0.869487 │
│ 123140303897433 ┆ -0.869487 │
│ 124325714300234 ┆ -0.869487 │
│ 124738035029214 ┆ -0.869487 │
└─────────────────┴───────────┘

In [9]:
test0 = submit.join(test0, on="event_id"
                         )
test0
#shape: (633_683, 69)

shape: (633_683, 71)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ event_id  ┆ predict   ┆ customer_ ┆ event_dtt ┆ … ┆ web_rdp_c ┆ compromis ┆ compromis ┆ compromi │
│ ---       ┆ ---       ┆ id        ┆ m         ┆   ┆ onnection ┆ ed_prev   ┆ ed_log_co ┆ sed_ses_ │
│ i64       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ _log_coun ┆ ---       ┆ unt       ┆ count    │
│           ┆           ┆ i64       ┆ datetime[ ┆   ┆ t         ┆ bool      ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ μs]       ┆   ┆ ---       ┆           ┆ f32       ┆ u16      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 123707242 ┆ -1.20836  ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.998672  ┆ true      ┆ 7.824846  ┆ 1        │
│ 230467    ┆           ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 14:55:11  ┆   ┆           ┆           ┆           ┆          │
│ 123234793 ┆ -1.409739 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999007  ┆ false     ┆ 6.284134  ┆ 2        │
│ 229123    ┆           ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 14:55:20  ┆   ┆           ┆           ┆           ┆          │
│ 125837545 ┆ -1.409739 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999343  ┆ true      ┆ 6.285998  ┆ 1        │
│ 055907    ┆           ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 14:55:28  ┆   ┆           ┆           ┆           ┆          │
│ 126456020 ┆ -1.20836  ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999679  ┆ true      ┆ 6.287858  ┆ 3        │
│ 999239    ┆           ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 14:56:28  ┆   ┆           ┆           ┆           ┆          │
│ 125090221 ┆ -1.124658 ┆ 123123123 ┆ 2025-07-0 ┆ … ┆ 8.066522  ┆ true      ┆ 6.93537   ┆ 1        │
│ 587312    ┆           ┆ 123130    ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 06:42:00  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 125528306 ┆ -0.984226 ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.428105  ┆ false     ┆ 6.013715  ┆ 353      │
│ 953183    ┆           ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 12:27:07  ┆   ┆           ┆           ┆           ┆          │
│ 123690063 ┆ 0.023269  ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.429719  ┆ false     ┆ 5.556828  ┆ 1        │
│ 072824    ┆           ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 16:47:31  ┆   ┆           ┆           ┆           ┆          │
│ 125734465 ┆ 0.90692   ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.431331  ┆ true      ┆ 5.560682  ┆ 1        │
│ 101827    ┆           ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 16:47:43  ┆   ┆           ┆           ┆           ┆          │
│ 125193299 ┆ 1.085379  ┆ 124265584 ┆ 2025-06-2 ┆ … ┆ 6.704414  ┆ true      ┆ 5.442418  ┆ 1        │
│ 828684    ┆           ┆ 425461    ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 02:47:37  ┆   ┆           ┆           ┆           ┆          │
│ 125657156 ┆ -0.869487 ┆ 124265584 ┆ 2025-06-2 ┆ … ┆ 6.705639  ┆ true      ┆ 5.446737  ┆ 1        │
│ 303168    ┆           ┆ 425461    ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 02:48:31  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
%%time
pool = Pool(data = test0.drop("customer_id",
                                      "event_id","event_dttm","session_id"
                               ).fill_null(-1
                               ).fill_null("null"
                               ).to_pandas(), 
                     )

CPU times: user 102 ms, sys: 120 ms, total: 223 ms
Wall time: 66.7 ms

In [11]:
model = CatBoostClassifier()
model.load_model(f"model00.cbm")

In [12]:
test0 = test0.with_columns(predict =  model.predict_proba(pool)[:,1])
test0

shape: (633_683, 71)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_id  ┆ predict  ┆ customer_ ┆ event_dtt ┆ … ┆ web_rdp_c ┆ compromis ┆ compromis ┆ compromis │
│ ---       ┆ ---      ┆ id        ┆ m         ┆   ┆ onnection ┆ ed_prev   ┆ ed_log_co ┆ ed_ses_co │
│ i64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ _log_coun ┆ ---       ┆ unt       ┆ unt       │
│           ┆          ┆ i64       ┆ datetime[ ┆   ┆ t         ┆ bool      ┆ ---       ┆ ---       │
│           ┆          ┆           ┆ μs]       ┆   ┆ ---       ┆           ┆ f32       ┆ u16       │
│           ┆          ┆           ┆           ┆   ┆ f32       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 123707242 ┆ 0.000024 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.998672  ┆ true      ┆ 7.824846  ┆ 1         │
│ 230467    ┆          ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 14:55:11  ┆   ┆           ┆           ┆           ┆           │
│ 123234793 ┆ 0.000233 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999007  ┆ false     ┆ 6.284134  ┆ 2         │
│ 229123    ┆          ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 14:55:20  ┆   ┆           ┆           ┆           ┆           │
│ 125837545 ┆ 0.000229 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999343  ┆ true      ┆ 6.285998  ┆ 1         │
│ 055907    ┆          ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 14:55:28  ┆   ┆           ┆           ┆           ┆           │
│ 126456020 ┆ 0.000321 ┆ 123123123 ┆ 2025-07-2 ┆ … ┆ 7.999679  ┆ true      ┆ 6.287858  ┆ 3         │
│ 999239    ┆          ┆ 123129    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 14:56:28  ┆   ┆           ┆           ┆           ┆           │
│ 125090221 ┆ 0.000159 ┆ 123123123 ┆ 2025-07-0 ┆ … ┆ 8.066522  ┆ true      ┆ 6.93537   ┆ 1         │
│ 587312    ┆          ┆ 123130    ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 06:42:00  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 125528306 ┆ 0.000794 ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.428105  ┆ false     ┆ 6.013715  ┆ 353       │
│ 953183    ┆          ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 12:27:07  ┆   ┆           ┆           ┆           ┆           │
│ 123690063 ┆ 0.000496 ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.429719  ┆ false     ┆ 5.556828  ┆ 1         │
│ 072824    ┆          ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 16:47:31  ┆   ┆           ┆           ┆           ┆           │
│ 125734465 ┆ 0.00092  ┆ 124265584 ┆ 2025-07-0 ┆ … ┆ 6.431331  ┆ true      ┆ 5.560682  ┆ 1         │
│ 101827    ┆          ┆ 425399    ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 16:47:43  ┆   ┆           ┆           ┆           ┆           │
│ 125193299 ┆ 0.000442 ┆ 124265584 ┆ 2025-06-2 ┆ … ┆ 6.704414  ┆ true      ┆ 5.442418  ┆ 1         │
│ 828684    ┆          ┆ 425461    ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 02:47:37  ┆   ┆           ┆           ┆           ┆           │
│ 125657156 ┆ 0.000807 ┆ 124265584 ┆ 2025-06-2 ┆ … ┆ 6.705639  ┆ true      ┆ 5.446737  ┆ 1         │
│ 303168    ┆          ┆ 425461    ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 02:48:31  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
test0.select("event_id","predict").write_csv('submit009logf.csv')